### ISSUE TITLE
imgComp 이미지 로딩 문제

### ISSUE THREAD

**Issue by jaehyeon74** [TamraZu/TamlaJu-Front#56]
### Description
---
리액트 쿼리로 해당 이미지 데이터를 가져와도 다른 페이지 이동했다가 원래 페이지로 돌아오면 이미지 로딩 표시가 뜹니다

### Todo
---
캐싱 기능 적용

**Comment by ramer-dev** [comment]
이건 잘 되고있지 않나용?
캐싱 이후에 발생하는 스피너(로딩 표시)는 캐시된 것을 불러올 때 발생한 시간 차 때문인것 같은데...
콘솔 창에 있는 disable cache 체크 되어있는지 확인해주세용!
![image](https://user-images.githubusercontent.com/51011193/234493793-5fcedf30-0e57-468c-b883-e8af74dc21bf.png)

**Comment by ramer-dev** [comment]
#60 에서 해결된 이슈.
